name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'

jobs:
  greet:
    runs-on: macos-latest
    
    steps:
    - name: Greet
      run: which ffmpeg
